version: "3"

services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=sphinx_emporium

  server:
    build: ./back-end
    depends_on:
      - "db"
    ports:
      - "8080:8080"

#  front-end:
#    build: ./front-end
#    depends_on:
#      - server
#    ports:
#      - "3000:3000"