version: "3"

services:
  server:
    build: ./back-end/database
    depends_on:
      - 'db'
    ports:
      - '8080:8080'
    networks:
      - ley_line_network
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=sphinx_emporium
    networks:
      - ley_line_network

networks:
  ley_line_network:
    driver: bridge